services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - .DOCKER_FILES/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: themembers
      MYSQL_PASSWORD: themembers
      MYSQL_DATABASE: themembers
      MYSQL_ROOT_PASSWORD: root
    networks:
      - platform_network
  php-fpm:
    container_name: php-fpm
    build:
      context: ./.DOCKER_FILES/php-fpm
    volumes:
      - ./:/var/www
      - ./.DOCKER_FILES/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - platform_network
    depends_on:
      - mysql
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
      PHP_IDE_CONFIG: "serverName=xdebug-docker"
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./.DOCKER_FILES/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.DOCKER_FILES/logs/nginx:/var/log/nginx
    networks:
      - platform_network
    depends_on:
      - php-fpm

networks:
  platform_network:
    ipam:
      driver: default
